echo Deleting node_modules...
rd /s /q node_modules

echo Deleting lock file...
del package-lock.json

echo Installing dependencies...
call npm install

echo Starting Expo...
call npx expo start --clear
